global:
  external_labels:
    server_name: prod
  scrape_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "node_exporter_centos"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9100"]
  - job_name: "pushgateway"
    honor_labels: true
    static_configs:
      - targets: ["localhost:9091"]
  - job_name: "blackbox-tcp"
    scrape_interval: 4s
    metrics_path: /probe # Это путь, который использует Blackbox Exporter.
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
          - 192.168.31.220:80 # Здесь вводим URL или IP-адрес целевого сайта.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115 # Указывается адрес Blackbox Exporter.
  - job_name: "nginx"
    static_configs:
      - targets:
          - 192.168.31.220:9113
alerting:
  alertmanagers:
    - static_configs:
        - targets: ["localhost:9093"]

rule_files:
  - alert.rules.yml

remote_write:
  - url: "http://192.168.31.220:8428/api/v1/write"

remote_read:
  - url: "http://192.168.31.220:8428/api/v1/read"
